### ISSUE TITLE
Links in text have no hover effect

### ISSUE THREAD

**Issue by Kilian** [captainbrosset/devtools-tips#111]
I added the text-decoration: none for them but it seems you opted to remove them. They need _some_ change on hover.

**Comment by captainbrosset** [comment]
Can you share more about the reasons behind adding a hover effect? There is one now, it's very subtle though. But I'm wondering if there's proven accessibility and/or ux design reasons why something more obvious would help.

**Comment by Kilian** [comment]
https://www.w3.org/WAI/WCAG21/Techniques/general/G183
