### ISSUE TITLE
find-expensive-selectors post is no longer valid

### ISSUE THREAD

**Issue by jantimon** [captainbrosset/devtools-tips#116]
https://devtoolstips.org/tips/en/find-expensive-selectors/

it seems like edge removed this feature from their devtools with the latest version

**Comment by captainbrosset** [comment]
Thanks for filing. Edge didn't remove the feature, it's unavailable because of a bug unfortunately. I hear that they're working on it right now and this should be fixed very soon. Can't wait for it to come back.

**Comment by jantimon** [comment]
oh that are good news 

thanks for letting me know
