### ISSUE TITLE
Search results container extends beyond page and doesn't scroll

### ISSUE THREAD

**Issue by MagnusOxlund** [captainbrosset/devtools-tips#124]
Tested on macOS 12.7.4 running Safari 17.4. 

<img width="1280" alt="Screenshot 2024-03-22 at 12 59 15" src="https://github.com/captainbrosset/devtools-tips/assets/10921083/5b1083ba-6a8d-4140-95f1-126cc6926521">

**Comment by captainbrosset** [comment]
Thanks so much for filing this. I'll need to take a look when I have some time. But if others want to jump in and help, they're very welcome to do so too.

**Comment by alystair** [comment]
@captainbrosset throw in the following to the pagefind-ui__drawer class (I don't use Svelte so I'm if that's the original class name): `max-height: min(calc(100vh - 7em),37em); overflow-y: scroll;`. You can tweak the numbers to increase the maximum height to your preference.
