### ISSUE TITLE
Make sure the "reporting bugs" tip is reviewed by the devtools teams

### ISSUE THREAD

**Issue by captainbrosset** [captainbrosset/devtools-tips#13]
I recently added a tip for people to know how to send feedback and report bugs/features with the various devtools teams: https://github.com/captainbrosset/devtools-tips/blob/main/src/tips/en/send-feedback-about-devtools.md

I would love it if the actual devtools teams involved would review the information in that tip, so they can confirm the links.

Pinging @nchevobbe for Firefox, @codepo8 for Edge, @mathiasbynens for Chrome and @oslego for Safari.
Let me know if the content of that md file feels good to you, and don't hesitate to let me know if you want to make changes. You can also directly open a PR and I'll get it merged quickly.

**Comment by mathiasbynens** [comment]
LGTM. If I would write this, I would've mentioned the Chromium issue tracker first, and then point folks towards the Edge feedback button only for Edge-only issues, rather than the other way around.

**Comment by oslego** [comment]
Thanks for creating this! The Bugzilla link for WebKit/Safari is good. That's the main intake for Safari Web Inspector bugs.

For Safari, the browser itself, there's an alternative [bug reporting tool](https://developer.apple.com/bug-reporting/) in Feedback Assistant (https://feedbackassistant.apple.com) for people who already have an Apple ID.

Both WebKit Bugzilla and Feedback Assistant are welcome for signaling bugs to the Safari, WebKit, and Safari Web Inspector teams.

**Comment by captainbrosset** [comment]
Thank you both. I have modified the wording slightly based on your feedback: https://github.com/captainbrosset/devtools-tips/commit/b9839c4cbfbe5a5796bd324bfb5226b8f1fda12b

**Comment by nchevobbe** [comment]
Looks perfect for Firefox, thanks Patrick!
