### ISSUE TITLE
Can't scroll through Search modal results

### ISSUE THREAD

**Issue by nchevobbe** [captainbrosset/devtools-tips#138]
1. Go to https://devtoolstips.org/
2. Make sure your browser height is small enough so that the page overflows
3. Search for "har" in the search input
4. Click on the load more results button if you see it

-> search results below the fold can't be accessed (even tabbing through results don't make them visible)

**Comment by nchevobbe** [comment]
Ah yes, sorry for the dupe, I should have checked the existing issues

**Comment by captainbrosset** [comment]
No worries, thanks for reporting! That's a good clue for me to try and fix this damn thing sooner rather than later.
