### ISSUE TITLE
Service worker issue?

### ISSUE THREAD

**Issue by pankajparashar** [captainbrosset/devtools-tips#34]
My primary browser consistently shows an outdated version of devtools-tips. I know this because if I open the site in Incognito, it always has one more tip than my primary browser. Is this a service worker issue?

<img width="843" alt="image" src="https://user-images.githubusercontent.com/38640616/184468458-3c1de13f-e7ad-49ca-952d-feffc0085a2a.png">

**Comment by captainbrosset** [comment]
Yes, that's probably a service worker issue. I implemented a background periodic sync as well, which runs once a day, so that could be related too. But I also remember making some changes recently where the worker would first try the network. So I'll have to check the code again. Thanks for filing!

**Comment by captainbrosset** [comment]
I removed the entire cache-first strategy since that's not really suited for this type of app. I still have the periodicsync, but the problem should now go away (after a couple of reloads, for the browser to pick up the new SW version).
