### ISSUE TITLE
Update browser support table for Snippets

### ISSUE THREAD

**Issue by pankajparashar** [captainbrosset/devtools-tips#41]
Link:
https://devtoolstips.org/tips/en/use-scripts-as-snippets/

Latest version of Safari Technology Preview 156 now supports running [Snippets](https://webkit.org/blog/13394/release-notes-for-safari-technology-preview-156/). AFAIK, Firefox has supported [running snippets](https://www.canidev.tools/run-snippets/firefox) via Console for a long time.

**Comment by captainbrosset** [comment]
Thanks Pankaj.

I don't have a recent-enough mac to test the latest Safari TP unfortunately. But if they do support snippets, then let's add this in.

One thing I'm wondering about though, and it's the same for Firefox, is whether these snippets can be saved.

The Chrome/Edge snippets can be persisted so you can use them on any webpage, whenever you want. 
Firefox kind of allows this with their console history search feature, but it's not exactly the same. So I'm kind of hesitant to add Firefox as a supported browser on that particular tip page.
The multi-line editor in Firefox is mentioned here though: https://devtoolstips.org/tips/en/multi-line-console/

And I just don't know how the Safari feature works.

**Comment by pankajparashar** [comment]
Yes Snippets are saved in Safari by default, similar to Chrome/Edge, although I don't know where in the filesystem these snippets are saved, but we do have the option to explicitly export it and save it on the filesystem. Ironically there is no option to Delete a snippet!

Demo:
![run-snippets-safari_p3udd4](https://user-images.githubusercontent.com/38640616/197749420-f99fcaf0-1af1-4e1a-9105-5bbff3db72cd.gif)

**Comment by pankajparashar** [comment]
Fair point on Firefox! 
To respect the title 'Re-use scripts as snippets', I agree we should not add Firefox into this list.

**Comment by captainbrosset** [comment]
I've updated https://devtoolstips.org/tips/en/use-scripts-as-snippets/ with your information, thanks! 
I've also left a note about Firefox and linked to the multi-line console tip from there.
