### ISSUE TITLE
Link author names to their place on the web

### ISSUE THREAD

**Issue by captainbrosset** [captainbrosset/devtools-tips#42]
The authors list at the bottom of each tip is just plain text that comes from the `authors` field in a tip's front matter.
Let's turn this into a list of links so that each author can really get credit for their work.

Idea: add a AUTHORS.json file somewhere in the repo that links each author's name to their place on the net.
Then at build time, convert the authors' field into a list of links. This way, each author can define where they want to be linked to, and this is in just one place.

**Comment by Kilian** [comment]
In https://github.com/captainbrosset/devtools-tips/pull/46 I added a [formatAuthor](https://github.com/captainbrosset/devtools-tips/pull/46/commits/1363ab4be77c3cb5ec85318697ee3d303a5075f8) template function that we can extend to get that data from AUTHORS.json and create links.

**Comment by captainbrosset** [comment]
This is great, thank you for working on this.
