### ISSUE TITLE
Make images clickable too

### ISSUE THREAD

**Issue by captainbrosset** [captainbrosset/devtools-tips#63]
In tip list pages, you need to click on either the tip title or the "read more" link. Being able to click the image would be great too.

**Comment by shyamtawli** [comment]
Hello @captainbrosset i can try my hands on it.  Please assign me.

**Comment by c00kie123** [comment]
Hello, I can work on this as well.

**Comment by captainbrosset** [comment]
Thanks both for your interest and quick replies.
Since @shyamtawli asked first, I'll assign the issue to them. Feel free to open a PR when you can.
Our contribution guidelines are here: https://github.com/captainbrosset/devtools-tips/blob/main/CONTRIBUTING.md

Let me know if you need any help.

**Comment by c00kie123** [comment]
Thanks for replying! Can I still open a PR or do I have to wait for @shyamtawli to do so ?

**Comment by captainbrosset** [comment]
Please do not open a PR for this issue, since it is already assigned to somebody else. This would create unnecessary duplicate work.
If you want to contribute the project, there are other issues available. #49 is a little more involved, but should be a good one to start with anyway. Feel free to comment there if you're interested and I can help you work on it.

**Comment by c00kie123** [comment]
No problem!

**Comment by shyamtawli** [comment]
@captainbrosset sorry but i can find the image render file can you please guide me through it because i have worked with nunjucks. i have find the link url render file.
Help me finding image render file.

**Comment by captainbrosset** [comment]
The file that renders a single tip in a list of tips on the site is this one: `src\includes\tip-in-list.njk`.

In this file, the `{% mainImage post %}` expression is the one that generates the image on the site. So, in theory, the idea is to wrap this expression in a `<a href>` link that goes to the post.

Does this help?

**Comment by shyamtawli** [comment]
Hey @captainbrosset  i have done the image part it will disturb the layout, so i have disable the grid property and it look nice to me. have a look and give feedback.
https://user-images.githubusercontent.com/104145978/212458699-41dd826c-56a5-4566-bd29-90368152c18c.mp4

**Comment by shyamtawli** [comment]
@captainbrosset have you checked?

**Comment by captainbrosset** [comment]
Thanks a lot for the quick work. I will check the code tomorrow. 
Could you open a Pull Request on the repo, with your changes?

**Comment by shyamtawli** [comment]
@captainbrosset sorry for replying late.
Currently my exams are going on.
so on 20 January i will make chances that you want.
Is that fine?

**Comment by captainbrosset** [comment]
Yes that's totally fine. No time pressure on my side. 
Just let me know if your plans change.

**Comment by captainbrosset** [comment]
This is now fixed. Closing!
