### ISSUE TITLE
Never pause at exceptions

### ISSUE THREAD

**Issue by pankajparashar** [captainbrosset/devtools-tips#66]
Right click on the line > Never pause here, seems to be a simpler & straight forward alternative to handle abusive [debugger statements](https://devtoolstips.org/tips/en/disable-abusive-debugger-statement/). Thoughts?

![image](https://user-images.githubusercontent.com/38640616/216872391-da47e211-c921-49bd-93b8-d6998501a614.png)

**Comment by captainbrosset** [comment]
Great point. I didn't think of this. Which browsers is this supported on? Did you test whether it worked in the `debugger` statement case?

**Comment by pankajparashar** [comment]
Yes it is supported well in all Chromium browsers. Recorded a video using your test script below,

![ScreenFlow](https://user-images.githubusercontent.com/38640616/217333916-2f5b90fe-2a98-4bc2-b35c-293f22dae6c6.gif)

**Comment by captainbrosset** [comment]
Thanks! I've added it to the tip: https://github.com/captainbrosset/devtools-tips/blob/main/src/tips/en/disable-abusive-debugger-statement.md

**Comment by amaramth** [comment]
doesn't work if `debugger` is in an anonymous function

where would be a good place to file an issue with chromium or firefox to ask for an option to disable `debugger` outright?

**Comment by captainbrosset** [comment]
@nchevobbe can you help me find the pref that makes it possible to disable all `debugger` breakpoints? Does it really just disable this expression, or does it also skips all other breakpoints?

**Comment by nchevobbe** [comment]
it's `devtools.debugger.pause-on-debugger-statement`, which is true by default. Setting it to false will only not pause at `debugger` statements.
It's also exposed in the UI: 
![CleanShot 2024-06-07 at 10 50 22](https://github.com/captainbrosset/devtools-tips/assets/578107/6e67c755-a68c-4493-a631-b90dd6b187e1)

There's another button to ignore all breakpoints: 
![CleanShot 2024-06-07 at 10 52 01](https://github.com/captainbrosset/devtools-tips/assets/578107/a67f4b9d-6459-4858-b763-3dfd19973e82)

**Comment by amaramth** [comment]
i toggled `devtools.debugger.enabled`
