### ISSUE TITLE
Disable debugger statement tip doesn't work in Safari

### ISSUE THREAD

**Issue by pankajparashar** [captainbrosset/devtools-tips#68]
I don't think setting a conditional breakpoint to `false` makes the debugger pause at the `debugger` statement in Safari, at least not when I tested. It works fine on other statements, but doesn't seem to work on the `debugger` statement itself.

Here is the repro: (maybe some webkit experts can chime in here)

https://user-images.githubusercontent.com/38640616/218023200-ac7a1b19-c1b9-40e8-a0f6-7007703ea9a8.mp4

**Comment by captainbrosset** [comment]
Thanks for reporting this Pankaj. I'll remove the Safari compat flag on this one for now.
