### ISSUE TITLE
Ignore JS code in Edge

### ISSUE THREAD

**Issue by pankajparashar** [captainbrosset/devtools-tips#75]
I may be missing something, but I didn't find the "Mark as library code" option in Edge [as instructed](https://devtoolstips.org/tips/en/ignore-scripts/) in the highlighted section below. I can see "Add script to ignore list" option similar to what Chrome has. Can you check?

![image](https://user-images.githubusercontent.com/38640616/226140002-826f47cb-5098-498c-bc95-85a4e565f0d5.png)

**Comment by captainbrosset** [comment]
Fixed with 28ef62a22c7066259af3cd0aea91eb5aa3c325f1.
