### ISSUE TITLE
Consider adding Safari and Polypane to the new print media emulation tip

### ISSUE THREAD

**Issue by captainbrosset** [captainbrosset/devtools-tips#79]
I just added this new tip: https://devtoolstips.org/tips/en/debug-print-css-styles/

I *think* this feature also works on Safari and Polypane, but I have no way of testing right now.
Would someone please test and, if the feature is indeed supported, submit a PR to add the necessary docs?

**Comment by captainbrosset** [comment]
cc @Kilian

**Comment by Kilian** [comment]
Yep Polypane has support: https://twitter.com/polypane/status/1268798800421847040

I'll amend it with steps later!

**Comment by captainbrosset** [comment]
For info, Kilian just added the info for Polypane. If someone wants to take care of this for Safari, that'd be great.

**Comment by pankajparashar** [comment]
Got a writeup here, https://www.canidev.tools/emulate-print-styles/safari

I'll add this to the tip page over the weekend.

**Comment by captainbrosset** [comment]
Thanks @pankajparashar for adding this! Closing this issue.
