### ISSUE TITLE
Replay XHR?

### ISSUE THREAD

**Issue by pankajparashar** [captainbrosset/devtools-tips#82]
I'm not sure if I'm missing a step, but I don't see the **Replay XHR** option on the XHR/Fetch requests in the Network panel.

https://devtoolstips.org/tips/en/replay-xhr/

<img width="870" alt="Screenshot 2023-06-10 at 21 33 14" src="https://github.com/captainbrosset/devtools-tips/assets/38640616/0f7fd69e-8f21-42ed-93db-9ba5979d1102">

**Comment by pankajparashar** [comment]
Pinging @bramus to check which version of Chrome Canary supports Replay XHR option?

**Comment by bramus** [comment]
Tested a few things and don’t see it in Chrome 114, 115, nor 116. Also tested Edge Canary 116.0.1923.0 to make sure it’s not a Edge DevTools specific thing, but also don’t see the option there. Maybe it’s an experiment?

Pinging @jecfish who’s on top of the Chrome DevTools side of things.

**Comment by pankajparashar** [comment]
@captainbrosset Thank you very much! Yes I can see this option now. I was naively testing this on the Fetch requests whereas I should have tested it for XHR requests. 

I agree this option should also be enabled for Fetch too, perhaps a separate option called `Replay Fetch` or maybe a generic option called `Replay Request` which works for both `XHR/Fetch`.
