### ISSUE TITLE
Search results are hidden below article contents

### ISSUE THREAD

**Issue by wanacode** [captainbrosset/devtools-tips#83]
When doing a search on the homepage, the results drawer is below the contents of the articles.

This appears to be related to the addition of  a `view-transition-name` which creates a new stacking context, so it is likely only an issue in browsers supporting the View Transitions API.

It looks like this can be resolved by giving `.pagefind-ui__drawer` a `z-index` of 1 or more .

![image](https://github.com/captainbrosset/devtools-tips/assets/2317149/7a8bbac0-bb46-4470-90a9-6d00399cbfba)

**Comment by captainbrosset** [comment]
Thanks so much for finding and reporting this. I added the view-transition code recently, but didn't think to test how it would impact the search box.
I'll add the necessary z-index to fix this. Thanks again!
