### ISSUE TITLE
Re: Take HD screenshots

### ISSUE THREAD

**Issue by pankajparashar** [captainbrosset/devtools-tips#90]
Tip:
https://devtoolstips.org/tips/en/take-high-res-screenshots/

Similar to Firefox, I discovered even the Chromium browsers allow you to select a Device-pixel ratio to take HD screenshots. Perhaps this is more inline with how Firefox does it. Should I add a PR to replace the existing trick for Chromium browsers?

<img width="372" alt="image" src="https://github.com/captainbrosset/devtools-tips/assets/38640616/a97ca325-d4f6-4e69-83eb-97c008a10fee">

<img width="799" alt="image" src="https://github.com/captainbrosset/devtools-tips/assets/38640616/8b9099ae-08fb-46be-9cd8-59d9fb9c860b">

**Comment by captainbrosset** [comment]
Oh cool. Yes, adding this to the existing tip would be great! Thanks Pankaj.
