### ISSUE TITLE
Debug popovers

### ISSUE THREAD

**Issue by pankajparashar** [captainbrosset/devtools-tips#96]
Following are the couple of ways to debug overlay elements like popups, dropdown lists etc. mentioned on Devtools Tips,

1. https://devtoolstips.org/tips/en/debug-js-hover/
2. https://devtoolstips.org/tips/en/debug-js-hover-2/

Perhaps a much simpler (or non-js) way is to use the _mysteriously named_ **Emulate a focused page** option in the Rendering drawer. [Related docs](https://developer.chrome.com/docs/devtools/rendering/apply-effects/#emulate-a-focused-page). 

I'm not sure if it deserves a separate page for the tip or do you prefer to add an addendum to the existing tips?

![nIXptxL1r7NezWQraJJ7](https://github.com/captainbrosset/devtools-tips/assets/38640616/a8a38f51-bd61-4e16-9b26-376dc16adb1b)

**Comment by captainbrosset** [comment]
Let's create a new tip about this, give it a descriptive title, and list the two other tips in the `see-also` section.
